spring.application.name=ollama
server.error.whitelabel.enabled=false
server.error.path=/error
server.forward-headers-strategy=native
spring.jackson.time-zone=UTC
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true
